<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Business\System.cs" CopyToOutputDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ControlLibrary\ControlLibrary.csproj" />
    <ProjectReference Include="..\Module.Communication\Module.Communication.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Features\StationConfiguration\StationConfigurationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Features\LuaScript\LuaScriptView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
